
package equipecincocadastroproduto;

/**
 *
 * @author Vini, Thomás
 */
        
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(153,204,255));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProdutos = new java.awt.Label();
        lblNome = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblResumo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResumo = new javax.swing.JTextArea();
        txtQuantidade = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        lblCadastro_produtos = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        tela = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblProdutos.setBackground(new java.awt.Color(153, 204, 255));
        lblProdutos.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        lblProdutos.setText("Produtos");

        lblNome.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblNome.setText("Nome:");

        lblTipo.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblTipo.setText("Tipo:");

        lblDescricao.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblQuantidade.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        lblResumo.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblResumo.setText("Resumo:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        txtResumo.setColumns(20);
        txtResumo.setRows(5);
        jScrollPane2.setViewportView(txtResumo);

        btnAlterar.setBackground(new java.awt.Color(255, 255, 153));
        btnAlterar.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 2, true));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(255, 153, 153));
        btnDeletar.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnIncluir.setBackground(new java.awt.Color(204, 255, 204));
        btnIncluir.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(153, 255, 255));
        btnListar.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        lblCadastro_produtos.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblCadastro_produtos.setText("Cadastro de Produtos");

        lblId.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        lblId.setText("Id:");

        tbDados.setBackground(new java.awt.Color(204, 204, 204));
        tbDados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Produto", "Tipo", "Nome", "Descrição", "Resumo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.setToolTipText("");
        tbDados.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tbDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(lblCadastro_produtos)
                .addGap(0, 289, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblQuantidade)
                            .addGap(30, 30, 30)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(lblId)
                                    .addGap(19, 19, 19)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(117, 117, 117)
                                    .addComponent(lblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(lblDescricao)
                                .addComponent(lblResumo)
                                .addComponent(lblTipo))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)
                                .addComponent(txtNome)
                                .addComponent(txtTipo)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(275, 275, 275)
                            .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastro_produtos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResumo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tela)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar)
                    .addComponent(btnIncluir)
                    .addComponent(btnDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String nome = txtNome.getText();
        String tipo = txtTipo.getText();
        String descricao = txtDescricao.getText();
        String resumo = txtResumo.getText();
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        int idProduto = Integer.parseInt(txtId.getText());
        
        Conexão banco = new Conexão("localhost","3306","cadastroProduto", "cadastroProduto", "cadastroProduto");
        banco.realizaConexao();
        
        if(banco.isStatusConexao()){
            CadastroProduto cadastro = new CadastroProduto(banco.getConexao());
            try{
                cadastro.setNome(nome);
                cadastro.setTipo(tipo);
                cadastro.setDescricao(descricao);
                cadastro.setResumo(resumo);
                cadastro.setQuantidade(quantidade);
                cadastro.setIdProduto(idProduto);
                cadastro.atualizaProdutos();
                tela.setText("Produto atualizado com sucesso!");
            }
            catch(SQLException e){
                tela.setText("Não foi possível atualizar o produto, erro: "+e.getMessage());
            }
        }
        else{
            System.out.println("Não está conectado. ");
            System.out.println(banco.getMensagemErro());
            
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        Conexão banco = new Conexão("localhost","3306","cadastroProduto", "cadastroProduto", "cadastroProduto");
        banco.realizaConexao();
    
        if(banco.isStatusConexao()){
            CadastroProduto cadastro = new CadastroProduto(banco.getConexao());
            int idProduto = Integer.parseInt(txtId.getText());
            try{
                cadastro.setIdProduto(idProduto);
                cadastro.removerProdutos();
                tela.setText("Produto removido com sucesso");
            }
            catch(SQLException e){
                tela.setText("Não foi possível remover o produto, erro: "+e.getMessage());
            }
        }
        else{
            System.out.println("Não está conectado.");
            System.out.println(banco.getMensagemErro());
        }        
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        String nome = txtNome.getText();
        String tipo = txtTipo.getText();
        String descricao = txtDescricao.getText();
        String resumo = txtResumo.getText();
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        
        Conexão banco = new Conexão("localhost","3306","cadastroProduto", "cadastroProduto", "cadastroProduto");
        banco.realizaConexao();
        
        if(banco.isStatusConexao()){
            CadastroProduto cadastro = new CadastroProduto(banco.getConexao());
            try{
                cadastro.setNome(nome);
                cadastro.setTipo(tipo);
                cadastro.setDescricao(descricao);
                cadastro.setResumo(resumo);
                cadastro.setQuantidade(quantidade);
                cadastro.incluiProduto();
                tela.setText("Produto incluído, obteve o id "+cadastro.getIdProduto());
            }
            catch(SQLException e){
                tela.setText("Não foi possível cadastrar o produto"+e.getMessage());
            }
        }
        else{
            System.out.println("Não está conectado");
            System.out.println(banco.getMensagemErro());
        }
              
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Conexão banco = new Conexão("localhost","3306","cadastroProduto", "cadastroProduto", "cadastroProduto");
        banco.realizaConexao();
    
        if(banco.isStatusConexao()){
            CadastroProduto cadastro = new CadastroProduto(banco.getConexao());
            try{
                ResultSet listaProdutos = cadastro.obterListaProdutos();
                DefaultTableModel modelo = (DefaultTableModel) tbDados.getModel();
                modelo.setNumRows(0);
                
                while(listaProdutos.next()){
                    modelo.addRow(new Object[]{listaProdutos.getInt("idProduto"), listaProdutos.getString("tipo"), listaProdutos.getString("nome"), listaProdutos.getString("descricao"), listaProdutos.getString("resumo"), listaProdutos.getInt("quantidade")});
                }
            }
            catch(SQLException e){
                tela.setText("Não foi listar os produtos "+e.getMessage());
            }
        }
        else{
            System.out.println("Não está conectado");
            System.out.println(banco.getMensagemErro());
        }
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCadastro_produtos;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private java.awt.Label lblProdutos;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblResumo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tbDados;
    private javax.swing.JLabel tela;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextArea txtResumo;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}